export const CHECKBOXENUM = {
  DISTINCTION: {MIN: 60, MAX: 100},
  FIRST: {MIN: 50, MAX: 60},
  SECOND: {MIN: 40, MAX: 50},
  FAIL: {MIN: 0, MAX: 40}
}

export const RESULTTYPE = {
  DISTINCTION: 'DISTINCTION',
  FIRST: 'FIRST',
  SECOND: 'SECOND',
  FAIL: 'FAIL'
}

export const SEARCH_STUDENT = 'SEARCH_STUDENT';
export const UPDATE_DATA = 'UPDATE_DATA';
